# TP 0

## Objectifs

* Comprendre les bases de la programmation Python :  
  * Variables, types de données, listes, ensembles et tuples.
  * Expressions conditionnelles et boucles
  * Trier
  * Dictionnaire
  * Fichiers et interaction avec les utilisateurs
  * Calculs mathématiques (matrices) avec NumPy

## Prérequis

- Python 3.x installé
- Jupyter Notebook ou JupyterLab
- Familiarité de base avec l'exécution de cellules de code

## Aperçu des exercices

| Exercice | Difficulté | Sujets |
|----------|------------|--------|
| Exercice 1 | ★ | Commentaires, variables, chaînes, listes, tuples, ensembles |
| Exercice 2 | ★ | Expressions conditionnelles, boucles, range |
| Exercice 3 | ★ | Tri, min/max, zip, enumerate |
| Exercice 4 | ★★ | Dictionnaires, interaction utilisateur |
| Exercice 5 | ★★★ | Opérations sur les fichiers |
| Exercice 6 | ★ | Bases de NumPy |

## Exercice 1 ★

### a\. Commentaires

Le symbole # est utilisé pour écrire un commentaire.

In [1]:
# Ceci est un commentaire
print("Bonjour")

Bonjour


### b\. Variables

Une variable est un nom symbolique qui fait référence à une valeur ou qui la contient, et cette valeur peut être de différents types de données tels que des nombres, des chaînes de caractères ou des objets.

In [2]:
# une variable
message = "le monde!"
print(message)

le monde!


Les variables sont utilisées pour stocker des valeurs qui peuvent être manipulées ; ici, **a** et **b** se voient attribuer des valeurs entières, et **c** stocke le résultat de leur addition, qui est ensuite affiché.

In [3]:
a = 10
b = 20
c = a + b
print(c)

30


Une variable se voit attribuer une valeur réél, puis est affichée.

In [4]:
# nombres réels
pi = 3.14
print(pi)

3.14


La fonction **type()** en Python est utilisée pour déterminer le type de données d'une variable ou d'une valeur.

In [5]:
# types de donnés
message1 = "Bonjour"
a = 12
pi = 3.14
print(type(message1))
print(type(a))
print(type(pi))

<class 'str'>
<class 'int'>
<class 'float'>


### c\. Concaténation de deux chaînes de caractères

La concaténation de chaînes en Python désigne le processus qui consiste à joindre plusieurs chaînes de caractères pour en créer une nouvelle. Cela peut être réalisé en utilisant l'opérateur **+**. Lorsque vous utilisez **+** entre deux chaînes, Python les combine en une seule chaîne.

In [6]:
# Concaténation de deux chaînes de caractères
message = "le monde!"
print("Bonjour" + message)

Bonjourle monde!


In [7]:
# Concaténation de deux chaînes de caractères
message1 = "Bonjour "
message2 = "le monde!"
print(message1 + message2)

Bonjour le monde!


In [8]:
# concaténation de deux variables de types de données différents
# opération + sur deux types de données différents

# Supprimer le commentaire ci-dessous et lancer le code
message1 = "Bonjour en Python"
a = 3
# print(message1 + a)

Pourquoi avez-vous obtenu cette erreur ? Dans le code suivant, nous corrigeons cette erreur.

In [9]:
# solution de concaténation entre deux variables de types de données différents
message1 = "Bonjour en Python "
a = 3
print(message1 + str(a))

Bonjour en Python 3


La conversion de type (ou type casting) désigne le processus de conversion d'un type de données en un autre.

**str(a)** convertit la variable entière **a** en une chaîne de caractères. Cela est nécessaire car vous ne pouvez pas concaténer directement une chaîne (message1) avec un entier (a) en utilisant l'opérateur **+** sans d'abord convertir l'entier en une chaîne.

### d\. Listes

Une liste est une collection d'éléments, qui peuvent être de types de données différents, entourée de crochets **[]** et séparée par des virgules.

In [10]:
a = [10, 20, 30, 40, 50]
print(a)

[10, 20, 30, 40, 50]


Les listes sont des collections ordonnées, et chaque élément d'une liste possède une position spécifique appelée indice. L'indexation permet d'accéder aux éléments individuels d'une liste en utilisant leur position.

L'indice du premier élément d'une liste est **0**, l'indice du deuxième élément est **1**, et ainsi de suite.

Les éléments d'une liste peuvent être accédés en spécifiant le nom de la liste suivi de crochets contenant l'indice de l'élément que vous souhaitez accéder.

In [11]:
a = [10, 20, 30, 40, 50]
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

10
20
30
40
50


In [12]:
# Supprimer le commentaire ci-dessous et lancer le code
a = [10, 20, 30, 40, 50]
# print(a[8])

Pourquoi avez-vous obtenu cette erreur ? L'erreur se produit car le code tente d'accéder à un élément de la liste **a** à l'indice **8**, qui n'existe pas. En Python (et dans de nombreux langages de programmation), l'indexation des listes commence à **0** et va jusqu'à **len(a) - 1**, où **len(a)** est le nombre d'éléments dans la liste **a**.

In [13]:
message1 = "Bonjour en Python "
print(message1[0])
print(message1[1])
print(message1[2])
print(message1[3])
print(message1[4])
print(message1[5])
print(message1[6])
print(message1[7])

B
o
n
j
o
u
r
 


Les chaînes de caractères se comportent comme des listes de caractères à bien des égards, vous pouvez donc accéder à des caractères individuels en utilisant l'indexation, tout comme vous le feriez avec des éléments dans une liste. La fonction **len()** est utilisée pour déterminer le nombre de caractères (ou d'éléments) dans la chaîne (ou la liste).

In [14]:
message1 = "Bonjour en Python "
print(len(message1))

18


Nous allons maintenant créer une liste d'entiers

In [15]:
a = [10, 20, 30, 40, 50]
print(len(a))

5


La fonction **len()** est utilisée pour déterminer le nombre d'éléments dans une liste (ou la longueur de tout objet itérable). Lorsque **len()** est appliquée à une liste, elle retourne le nombre d'éléments (ou d'articles) présents dans cette liste.

In [16]:
a = [10, 20, 30, 40, 50]

# ajouter un nouveau numéro à la fin de la liste
a.append(60)
print(a)

[10, 20, 30, 40, 50, 60]


La méthode **append()** est utilisée pour ajouter un élément unique à la fin d'une liste existante. La syntaxe pour utiliser **append()** est **list_name.append(element)**, où **list_name** est le nom de la liste à laquelle vous souhaitez ajouter l'élément, et **element** est l'élément que vous voulez ajouter. L'élément peut être de n'importe quel type de données, et il est ajouté en tant que dernier élément de la liste.

Les éléments d'une liste peuvent être modifiés en attribuant une nouvelle valeur à un indice spécifique. L'indexation des listes commence à **0**, donc **a[0]** fait référence au premier élément de la liste **a**, **a[1]** fait référence au deuxième élément, et ainsi de suite. Vous pouvez directement attribuer une nouvelle valeur à n'importe quel élément existant dans la liste en utilisant cette méthode d'indexation.

In [17]:
a = [10, 20, 30, 40, 50]

# modifier un numéro à un index donné
a[0] = 0
print(a)

[0, 20, 30, 40, 50]


In [18]:
# Supprimer le commentaire ci-dessous et lancer le code
a = [10, 20, 30, 40, 50]

# a[6] = 20
print(a)

[10, 20, 30, 40, 50]


La méthode **insert()** peut être utilisée pour insérer un élément à n'importe quel indice dans la plage actuelle de la liste. Si vous spécifiez un indice supérieur à la longueur actuelle de la liste, Python insérera le nouvel élément à la fin de la liste.

In [19]:
a = [10, 20, 30, 40, 50]

# l'insertion d'un élément à un index particulier modifiera la liste
a.insert(0, 0)
print(a)
print(len(a))

[0, 10, 20, 30, 40, 50]
6


In [20]:
a = [10, 20, 30, 40, 50]
a.insert(6, 60)
print(a)
print(len(a))

[10, 20, 30, 40, 50, 60]
6


In [21]:
a = [10, 20, 30, 40, 50]

# Nous allons maintenant essayer d'insérer un nombre à un index plus grand que la longueur
# de la liste. Nous veillerons à ce qu'il n'y ait pas d'erreur et le nouveau numéro
# est ajouté à la fin de la liste
a.insert(10, 60)
print(a)
print(len(a))

[10, 20, 30, 40, 50, 60]
6


### e\. Tuples (listes non modifiables)



Un **tuple** est une collection ordonnée d'éléments, similaire à une liste, mais les tuples sont immutables, ce qui signifie que leur contenu ne peut pas être modifié après leur création. Les tuples sont définis en utilisant des parenthèses **()** et les éléments sont séparés par des virgules. Les tuples peuvent contenir des éléments de différents types de données et peuvent même contenir d'autres tuples.

In [22]:
a = (10, 20, 30, 40, 50)
print(a)

(10, 20, 30, 40, 50)


In [23]:
a = (10, 20, 30, 40, 50)
print(a[0])

10


In [24]:
a = (10, 20, 30, 40, 50)


# Nous essayons maintenant de modifier un tuple
# Décommentez le code ci-dessous et lancez le code
# Un tuple est une liste non modifiable

# a[0] = 0
print(a)

(10, 20, 30, 40, 50)


Les tuples en Python sont immuables, ce qui signifie que leur contenu ne peut pas être modifié après leur création. Cela contraste avec les listes, qui sont mutables et permettent de modifier leurs éléments.

### f\. Sets (Ensembles)



Un **ensemble** (set) est une collection non ordonnée d'éléments uniques. Il ne permet pas les éléments en double. Les ensembles sont définis en utilisant des accolades **{}**, et les éléments sont séparés par des virgules.

Lorsque vous créez un ensemble avec des éléments en double, Python supprime automatiquement les doublons, ne laissant que des éléments uniques dans l'ensemble.

In [25]:
# Un ensemble(Set) est une collection d'éléments distincts

a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
print(a)

{50, 20, 40, 10, 30}


Vous pouvez ajouter des éléments à un ensemble en utilisant la méthode **add()** et supprimer des éléments d'un ensemble en utilisant la méthode **remove()**.

In [26]:
a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
a.add(10)
print(a)

{50, 20, 40, 10, 30}


In [27]:
a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
a.add(60)
print(a)

{50, 20, 40, 10, 60, 30}


In [28]:
a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
a.remove(40)
print(a)

{50, 20, 10, 30}


Nous allons maintenant essayer différents types de données avec les chiffres et afficher le résultat.

In [29]:
# set
a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
print(a)
print(type(a))

# tuple
b = (10, 20, 30, 40, 50, 10, 20, 30, 40, 50)
print(b)
print(type(b))

# list
c = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
print(c)
print(type(c))

{50, 20, 40, 10, 30}
<class 'set'>
(10, 20, 30, 40, 50, 10, 20, 30, 40, 50)
<class 'tuple'>
[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
<class 'list'>


Les **ensembles** (sets) en Python suppriment automatiquement les doublons. Les **tuples** préservent l'ordre des éléments et permettent les doublons, mais sont immuables. Les **listes** préservent également l'ordre des éléments et permettent les doublons.

### **union()**
La méthode **union()** ou l'opérateur **|** combine deux ensembles en un nouvel ensemble contenant tous les éléments uniques des deux ensembles. Elle retourne un nouvel ensemble contenant les éléments présents dans **a**, **b**, ou les deux, sans doublons. L'opération d'union ne modifie pas les ensembles originaux **a** et **b** ; elle crée et retourne plutôt un nouvel ensemble avec les éléments combinés.

In [30]:
a = {10, 20, 30, 40, 50}
b = {10, 60, 70, 80, 90}
c = a.union(b)
print(c)

{70, 40, 10, 80, 50, 20, 90, 60, 30}


### **intersection()**
La méthode **intersection()** ou l'opérateur **&** retourne un nouvel ensemble contenant les éléments présents dans les deux ensembles **a** et **b**. Elle calcule l'intersection des ensembles **a** et **b**, ce qui signifie qu'elle inclut uniquement les éléments communs aux deux ensembles.

L'opération d'intersection ne modifie pas les ensembles originaux **a** et **b** ; elle crée et retourne plutôt un nouvel ensemble avec les éléments communs.

In [31]:
a = {10, 20, 30, 40, 50}
b = {10, 60, 70, 80, 90}
c = a.intersection(b)
print(c)

{10}


### **difference()**
La méthode **difference()** ou l'opérateur **-** retourne un nouvel ensemble contenant les éléments présents dans l'ensemble **a** mais pas dans l'ensemble **b**. Elle calcule la différence entre les ensembles **a** et **b**, ce qui signifie qu'elle inclut uniquement les éléments de **a** qui ne sont pas présents dans **b**.

L'opération de différence ne modifie pas les ensembles originaux **a** et **b** ; elle crée et retourne plutôt un nouvel ensemble avec les éléments de **a** qui ne sont pas dans **b**.

In [32]:
a = {10, 20, 30, 40, 50}
b = {10, 60, 70, 80, 90}
c = a.difference(b)
print(c)

{40, 50, 20, 30}


In [33]:
a = {10, 20, 30, 40, 50}
b = {10, 60, 70, 80, 90}
c = b.difference(a)
print(c)

{80, 90, 60, 70}


**Question :**

Étant donné les ensembles :

In [34]:
a = {10, 20, 30, 40, 50}
b = {15, 25, 35, 40, 50}
c = {5, 10, 15, 25, 30}

1. Trouvez l'intersection de `a` et `b`.
2. Trouvez la différence entre `b` et `a`.
3. Trouvez la différence symétrique entre `a` et `c`.
4. Déterminez si `a` est un sur-ensemble de `c`.
5. Trouvez l'union de l'intersection de `a` et `b` avec la différence de `b` et `c`.

Écrivez le code Python pour chaque opération et expliquez les résultats.

## Exercice 2 ★

### a\. Expressions conditionnelles


Les **instructions conditionnelles** (if, else, elif) vous permettent de contrôler le flux de votre programme en fonction de certaines conditions. Ces instructions vous aident à exécuter des blocs de code spécifiques en fonction du fait que les conditions soient vraies ou fausses.

### **L'instruction if**
L'instruction **if** est utilisée pour exécuter un bloc de code uniquement si une condition spécifiée est vraie. Elle peut être suivie d'un bloc **else** optionnel.

In [35]:
a = 12
if a % 2 == 0:
    print(a, " is divisible by 2")
else:
    print(a, " is not divisible by 2")

12  is divisible by 2


In [36]:
lang = "Français"
if lang == "Français":
    print("Bonjour le monde!")
else:
    print("Hello World!")

Bonjour le monde!


#### L'instruction `if-elif-else`

L'instruction **`if-elif-else`** est utilisée lorsque vous avez plusieurs conditions à évaluer de manière séquentielle. Elle vous permet de vérifier plusieurs conditions et d'exécuter un bloc de code dès qu'une des conditions est **True**. Elle peut également avoir un bloc **`else`** optionnel à la fin.

**Syntaxe :**
```python
if condition1:
    # bloc de code à exécuter si condition1 est True
elif condition2:
    # bloc de code à exécuter si condition2 est True (optionnel)
elif condition3:
    # bloc de code à exécuter si condition3 est True (optionnel)
else:
    # bloc de code à exécuter si toutes les conditions sont False (optionnel)
```

In [37]:
b = 15

if b < 10:
    print("b is less than 10")
elif b == 10:
    print("b is equal to 10")
else:
    print("b is greater than 10")

b is greater than 10


#### L'instruction `if-elif` (sans `else`)

Vous pouvez également utiliser **`if-elif`** sans bloc **`else`**. Dans ce cas, si aucune des conditions n'est **True**, aucun bloc de code ne sera exécuté.

**Syntaxe :**
```python
if condition1:
    # bloc de code à exécuter si condition1 est True
elif condition2:
    # bloc de code à exécuter si condition2 est True (optionnel)
```

In [38]:
c = 5

if c < 0:
    print("c is negative")
elif c == 0:
    print("c is zero")
elif c > 0:
    print("c is positive")

c is positive


### Points clés :

- Utilisez **`if`** pour exécuter un bloc de code en fonction d'une seule condition.
- Utilisez **`if-elif-else`** pour évaluer plusieurs conditions de manière séquentielle et exécuter le bloc de code correspondant dès qu'une condition est **True**.
- Utilisez **`if-elif`** sans **`else`** lorsque vous avez plusieurs conditions à vérifier, mais que vous n'avez pas besoin d'exécuter de code si aucune des conditions n'est **True**.
- L'**indentation** est cruciale en Python pour délimiter les blocs de code au sein des instructions conditionnelles.

Les instructions conditionnelles sont essentielles pour contrôler la logique et le comportement de vos programmes Python en fonction de différents scénarios et conditions.

### b\. Boucles

Les boucles peuvent également être utilisées pour accéder aux éléments à différents indices. Une **boucle `for`** est utilisée pour itérer sur une séquence (par exemple, une liste, un tuple, une chaîne de caractères ou une plage de nombres). La variable de boucle (**`i`** dans ce cas) prend chaque élément de la séquence un par un, ce qui vous permet d'effectuer des opérations sur chaque élément à l'intérieur de la boucle.

In [39]:
# liste
for i in [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]:
    print(i)

10
20
30
40
50
10
20
30
40
50


In [40]:
# tuples
for i in (10, 20, 30, 40, 50, 10, 20, 30, 40, 50):
    print(i)

10
20
30
40
50
10
20
30
40
50


In [41]:
# set
for i in {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}:
    print(i)

40
10
50
20
30


### c\. Limites



La fonction **`range(start, stop)`** génère une séquence de nombres en commençant par **`start`** jusqu'à (mais sans inclure) **`stop`**.

In [42]:
for i in range(0, 10):
    print(i)

0
1
2
3
4
5
6
7
8
9


**`range(start, stop, step)`** spécifie l'incrément (ou le décrément) entre chaque nombre dans la séquence. Le paramètre **`step`** détermine la différence entre chaque nombre successif dans la séquence.

In [43]:
for i in range(0, 10, 2):
    print(i)

0
2
4
6
8


In [44]:
# print() par défaut affiche le message suivi d'une nouvelle ligne
# Mais vous pouvez changer son comportement

for i in range(0, 10, 2):
    print(i, end=" ")

0 2 4 6 8 

Lorsque la valeur de **`step`** est négative (par exemple, **`-2`** dans l'exemple ci-dessous), la séquence compte à l'envers, c'est-à-dire qu'elle diminue.

In [45]:
for i in range(10, 0, -2):
    print(i)

10
8
6
4
2


In [46]:
for i in range(10, 0):
    print(i)

**`print()`** affiche par défaut le message suivi d'un saut de ligne. Cependant, vous pouvez modifier ce comportement. Le paramètre **`end=" "`** dans **`print()`** spécifie que chaque instruction **`print()`** doit se terminer par un espace au lieu du caractère de saut de ligne par défaut (**`\n`**).

In [47]:
for i in range(0, 10, 2):
    print(i, end=" ")

0 2 4 6 8 

#### d. split()

split(): La fonction peut être utilisée pour séparer une chaîne de caractères en utilisant 
un délimiteur spécifié. Par défaut, le délimiteur est un espace blanc.

In [48]:
for i in "Bonjour,le,monde!".split():
    print(i)

Bonjour,le,monde!


La boucle `for` parcourt chaque élément de la liste produite par `split()`, vous permettant de traiter chaque sous-chaîne individuellement.

In [49]:
for i in "Bonjour,le,monde!".split(","):
    print(i)

Bonjour
le
monde!


**Question 1**: Écrivez un programme en Python pour afficher la sortie suivante:

```
1
12
123
1234
12345
123456
1234567
12345678
```

**Indice**: Utilisez des boucles imbriquées. La boucle externe contrôle le nombre de lignes, et la boucle interne contrôle ce qui est affiché sur chaque ligne.

**Question 2**: Convertissez le code suivant en une seule compréhension de liste :

```python
result = []
for i in range(1, 11):
    if i % 2 == 0:
        result.append(i * i)
```

**Question 3**: En utilisant une compréhension de liste, extrayez tous les mots qui commencent par une majuscule de cette liste :
```python
words = ["Apple", "banana", "Cherry", "date", "Elderberry", "fig"]
```

**Indice**: Utilisez la méthode de chaîne `isupper()` pour vérifier si un caractère est en majuscule.

### e. Compréhensions de liste

Les compréhensions de liste fournissent un moyen concis de créer des listes. Elles sont plus lisibles et souvent plus rapides que les boucles for traditionnelles.

In [50]:
# Méthode traditionnelle pour créer une liste de carrés
carres = []
for i in range(10):
    carres.append(i ** 2)
print("Traditionnel:", carres)

# Avec une compréhension de liste - plus concis et Pythonique
carres_comp = [i ** 2 for i in range(10)]
print("Compréhension de liste:", carres_comp)

Traditionnel: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
Compréhension de liste: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


Les compréhensions de liste peuvent également inclure des conditions pour filtrer les éléments :

In [29]:
# Extraire uniquement les nombres pairs d'une liste
nombres = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
nombres_pairs = [x for x in nombres if x % 2 == 0]
print("Nombres pairs:", nombres_pairs)

# Extraire les mots de plus de 3 caractères
mots = ["Bonjour", "le", "monde", "je", "programme", "en", "Python"]
mots_longs = [mot for mot in mots if len(mot) > 3]
print("Mots longs:", mots_longs)

Nombres pairs: [2, 4, 6, 8, 10]
Mots longs: ['Bonjour', 'monde', 'programme', 'Python']


## Exercice 3 ★

### a\. Tri



La méthode **`sort()`** est utilisée pour trier les listes. Par défaut, **`sort()`** organise les éléments par ordre croissant.

In [30]:
num = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
num.sort()
print(num)

[10, 10, 20, 20, 30, 30, 40, 40, 50, 50]


### b\. Tri (ordre décroissant)



Passer **`reverse=True`** trie les éléments par ordre décroissant. La méthode **`sort()`** modifie directement la liste sans renvoyer une nouvelle liste.

In [53]:
num = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
num.sort(reverse=True)
print(num)

[50, 50, 40, 40, 30, 30, 20, 20, 10, 10]


### c\. minimum



La fonction **`min()`** renvoie l'élément le plus petit d'une séquence. Elle peut être utilisée directement avec des listes (ou d'autres objets itérables) pour trouver l'élément le plus petit.

In [54]:
num = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
print(min(num))

10


### d\. maximum



La fonction **`max()`** renvoie l'élément le plus grand d'une séquence. Elle peut être utilisée directement avec des listes (ou d'autres objets itérables) pour trouver l'élément le plus grand.

In [31]:
num = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
print(max(num))

50


### e\. sorted()

La fonction **`sorted()`** en Python peut être utilisée pour créer une nouvelle liste triée sans modifier la liste originale. Elle permet d'obtenir une version triée d'une liste sans altérer la liste d'origine.

Cette approche est utile lorsque vous avez besoin à la fois de la liste originale non triée et d'une version triée pour différents usages.

In [56]:
num = [70, 20, 30, 10, 50, 60, 20, 80, 70, 50]
tri = sorted(num, reverse=True)
print(num)
print(tri)

[70, 20, 30, 10, 50, 60, 20, 80, 70, 50]
[80, 70, 70, 60, 50, 50, 30, 20, 20, 10]


### f. reversed()

La fonction `reversed()` inverse l'ordre des éléments dans une séquence sans modifier la liste d'origine. Le résultat de `reversed()` est un itérateur, ce qui signifie qu'il génère les éléments de manière paresseuse, au fur et à mesure des besoins.

In [57]:
a = [12, 13, 14, 15]
a_reverse = reversed(a)

print(a_reverse)

for num in a_reverse:
    print(num)

15
14
13
12


### g. zip()

La fonction `zip()` associe les éléments de plusieurs itérables (listes, tuples, etc.) en fonction de leurs positions. Si les itérables d'entrée (`a1` et `b1` dans l'exemple ci-dessous) ont des longueurs différentes, `zip()` s'arrête après que le plus court soit épuisé.

`zip()` est couramment utilisé pour itérer simultanément sur plusieurs listes ou pour combiner des données provenant de différentes sources en tuples.

In [58]:
a1 = [1, 2, 3, 4]
b1 = [5, 6, 7, 8]

zipped = list(zip(a1, b1))
print(zipped)

[(1, 5), (2, 6), (3, 7), (4, 8)]


### h. enumerate()

La fonction `enumerate()` en Python est utilisée pour ajouter un compteur à un objet itérable (comme une liste, un tuple ou une chaîne de caractères) et le retourner sous forme d'objet `enumerate`.

Cet objet `enumerate` peut ensuite être utilisé dans des boucles ou d'autres itérations pour obtenir une liste d'éléments indexés.

In [59]:
a1 = [1, 2, 3, 4]

ezipped = enumerate(a1)
print(ezipped)

In [60]:
a1 = [1, 2, 3, 4]

ezipped = enumerate(a1)
for index, number in ezipped:
    print(index, number)

0 1
1 2
2 3
3 4


Elle peut également être utilisée avec d'autres fonctions mentionnées ci-dessus.

In [61]:
a1 = [1, 2, 3, 4]
b1 = [5, 6, 7, 8]

ezipped = list(enumerate(zip(a1, b1)))
print(ezipped)

[(0, (1, 5)), (1, (2, 6)), (2, (3, 7)), (3, (4, 8))]


### i. Chaîne de caractères

**sorted(..., key=str.lower, reverse=True)** : La fonction `sorted()` trie une liste. L'argument `key=str.lower` permet de trier les mots sans tenir compte de la casse (majuscules/minuscules). L'argument `reverse=True` indique que le tri doit être effectué en ordre décroissant (inverse).

In [62]:
print(sorted("Bonjour le monde!".split(), key=str.lower, reverse=True))

['monde!', 'le', 'Bonjour']


In [63]:
days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
days_num = list(enumerate(days))
print(days_num)

[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')]


`enumerate(days, start=1)` crée un objet `enumerate` qui itère sur les jours, en commençant l'index à partir de 1 `(start=1)`.

In [64]:
days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

days_num = list(enumerate(days, start=1))
print(days_num)

[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')]


**Question 1:**  Modifiez le code donné ci-dessous pour afficher les cinq plus grands numéros uniques.


In [65]:
num = [70, 20, 30, 10, 50, 60, 20, 80, 70, 50]

# sélectionner les cinq premiers numéros
tri = sorted(num, reverse=True)[:5]
print(tri)

[80, 70, 70, 60, 50]


**Question 2**

On vous donne une liste d'entiers représentant les chiffres de ventes mensuelles d'une entreprise sur une période de 12 mois. Votre tâche consiste à effectuer une série d'opérations en utilisant les fonctions de tri et de min/max pour analyser et manipuler les données.

In [66]:
sales = [1200, 3500, 2800, 4500, 3000, 2200, 3400, 3700, 4200, 3600, 2800, 3900]


1. **Trouvez le mois avec les ventes les plus élevées**.
2. **Trouvez le mois avec les ventes les plus faibles**.
3. **Triez les données de ventes** par ordre croissant (du plus petit au plus grand).
4. **Triez les données de ventes** par ordre décroissant (du plus grand au plus petit).
5. **Créez une nouvelle liste** des 3 mois avec les ventes les plus élevées. Affichez cette nouvelle liste.
6. **Créez une nouvelle liste** des 3 mois avec les ventes les plus faibles en utilisant la fonction `sorted()` sans `reverse=True` et en tranchant le résultat. Affichez cette nouvelle liste.
7. **Triez les données de ventes** en utilisant la fonction `sorted()` par ordre décroissant et créez une nouvelle liste contenant les données de ventes **sans les 2 premiers mois**. Affichez cette nouvelle liste.
8. Écrivez une fonction `average_sales()` qui calcule et retourne la moyenne des ventes sur les 12 mois. Utilisez cette fonction pour afficher la moyenne des ventes et comparez-la avec les chiffres des ventes les plus élevées et les plus faibles.

## Exercice 4 ★★

### a\. Dictionnaire

Un dictionnaire représente une collection non ordonnée d'éléments où chaque élément est une paire clé-valeur. Les clés doivent être uniques et immuables (chaînes de caractères, nombres, tuples), tandis que les valeurs peuvent être de n'importe quel type de données et peuvent être mutables.

In [67]:
a = {"contente": 12, "content": 12, "triste": 2}
print(a)
print(type(a))

{'contente': 12, 'content': 12, 'triste': 2}
<class 'dict'>


Vous pouvez accéder (et même modifier) à la valeur associée à une clé en utilisant `a[key]`.

In [68]:
a = {"contente": 12, "content": 12, "triste": 2}
a["contente"] = 10
print(a)

{'contente': 10, 'content': 12, 'triste': 2}


Itérer directement sur un dictionnaire permet d'itérer sur ses clés par défaut.

In [69]:
a = {"contente": 12, "content": 12, "triste": 2}
for key in a:
    print("la phrase ", key, " apparait ", a[key], " fois")

la phrase  contente  apparait  12  fois
la phrase  content  apparait  12  fois
la phrase  triste  apparait  2  fois


In [70]:
a = {"contente": 12, "content": 12, "triste": 2}
a["joie"] = 10
print(a)

{'contente': 12, 'content': 12, 'triste': 2, 'joie': 10}


Trier directement un dictionnaire avec `sorted()` trie ses clés et les retourne sous forme de liste.

In [71]:
mots = {"contente": 12, "content": 12, "triste": 2, "joie": 10}
print(sorted(mots))

['content', 'contente', 'joie', 'triste']


L'utilisation de `.items()` permet d'itérer sur les paires clé-valeur d'un dictionnaire.

In [72]:
a = {"contente": 12, "content": 12, "triste": 2}
for key, value in a.items():
    print("la phrase ", key, " apparait ", value, " fois")

la phrase  contente  apparait  12  fois
la phrase  content  apparait  12  fois
la phrase  triste  apparait  2  fois


In [73]:
mots = {"contente": 12, "content": 12, "triste": 2, "joie": 10}
mots_tuple = [(key, value) for key, value in mots.items()]
print(mots_tuple)

[('contente', 12), ('content', 12), ('triste', 2), ('joie', 10)]


Vous pouvez supprimer un élément d'un dictionnaire en utilisant `del` suivi de `a[key]`, où `key` est la clé de l'élément que vous souhaitez supprimer.

In [74]:
a = {"contente": 12, "content": 12, "triste": 2}
del a["triste"]
print(a)

{'contente': 12, 'content': 12}


### b\. itemgetter

`itemgetter` est une fonction du module `operator` qui est utilisée pour récupérer des éléments ou des objets d'un objet itérable (comme une liste, un tuple ou un dictionnaire) en fonction de leurs indices ou clés. Elle renvoie un objet callable qui extrait l'élément ou les éléments spécifiés de l'objet fourni.

Utiliser `sorted()` avec `itemgetter(1)` permet de trier une liste de tuples en fonction du deuxième élément (ici, la `valeur`). Les opérations de tri ne modifient pas le dictionnaire d'origine ni son contenu, mais créent une liste triée de tuples.

In [75]:
from operator import itemgetter

mots = {"contente": 12, "content": 12, "triste": 2, "joie": 10}
mots_tuple = [(key, value) for key, value in mots.items()]
print(sorted(mots_tuple, key=itemgetter(1)))

[('triste', 2), ('joie', 10), ('contente', 12), ('content', 12)]


### c. Fonctions

Une fonction est un bloc de code réutilisable qui effectue une tâche spécifique. Les fonctions aident à organiser le code, le rendre réutilisable et plus facile à comprendre.

In [76]:
# Définir une fonction simple
def saluer(nom):
    """Cette fonction salue la personne passée en paramètre"""
    return f"Bonjour, {nom}!"

# Appeler la fonction
message = saluer("Python")
print(message)

Bonjour, Python!


Les fonctions peuvent avoir plusieurs paramètres et des valeurs par défaut :

In [77]:
# Fonction avec plusieurs paramètres et une valeur par défaut
def calculer_moyenne(nombres, decimales=2):
    """Calcule la moyenne d'une liste de nombres"""
    if len(nombres) == 0:
        return 0
    moy = sum(nombres) / len(nombres)
    return round(moy, decimales)

notes = [85, 90, 78, 92, 88]
print("Moyenne des notes:", calculer_moyenne(notes))
print("Moyenne des notes (4 décimales):", calculer_moyenne(notes, 4))

Moyenne des notes: 86.6
Moyenne des notes (4 décimales): 86.6


### d. Interaction avec l'utilisateur

La fonction `input()` est utilisée pour accepter les entrées de l'utilisateur depuis la console. Le message à l'intérieur de `input()` sert d'invite pour guider l'utilisateur sur ce qu'il doit saisir.

In [78]:
# nom = input("Quel est votre nom?")
# print(nom)

In [79]:
# age = input("Quel est votre âge? ")
# print(age)
# print(type(age))

In [80]:
# age = input("Quel est votre âge? ")
# age = int(age)
# print(age)
# print(type(age))

**Question 1: Compréhension de l'ensemble et filtrage complexe**

Vous avez une collection de données d'utilisateurs stockées sous forme de liste de dictionnaires. Chaque dictionnaire représente un utilisateur avec les clés suivantes : name, age et hobbies.

In [81]:
users = [
    {"name": "Alice", "age": 30, "hobbies": {"reading", "swimming", "hiking"}},
    {"name": "Bob", "age": 22, "hobbies": {"chess", "reading", "swimming"}},
    {"name": "Charlie", "age": 25, "hobbies": {"gaming", "hiking", "reading"}},
    {"name": "Diana", "age": 35, "hobbies": {"swimming", "yoga", "reading"}},
    {"name": "Eve", "age": 29, "hobbies": {"gaming", "reading", "chess"}},
]

1. Écrivez un programme qui :
   - Trouve les **loisirs (hobbies) communs** à tous les utilisateurs.
   - Trouve les **loisirs uniques** (ceux qui n'appartiennent qu'à un seul utilisateur).
   - Trouve les utilisateurs qui partagent les **exactement les mêmes loisirs** (s'il y en a).
   - Trouve le **loisir le plus populaire** parmi tous les utilisateurs.
   
2. Affichez les résultats clairement et expliquez votre approche.

**Question 2:** Écrivez un programme en Python qui interagit avec l'utilisateur pour
obtenir les informations suivantes de 5 étudiants :

- Nom de l'étudiant
- Âge
- Notes en 5 modules

Une fois les informations obtenues pour les cinq étudiants, calculez
et affichez les valeurs suivantes pour chaque module :

- note moyenne
- note maximale
- note minimale

**Question 3:** Refactorisez votre solution en utilisant des fonctions :

1. Créez une fonction `obtenir_info_etudiant()` qui collecte et retourne les informations d'un étudiant
2. Créez une fonction `calculer_stats_module(notes)` qui prend une liste de notes et retourne un dictionnaire avec moyenne, max et min
3. Créez une fonction `afficher_stats(stats)` qui affiche les statistiques de manière formatée

**Indice:** L'utilisation de fonctions rend votre code réutilisable et plus facile à tester.

## Exercice 5 ★★★

Lire et écrire dans un fichier

### a\. Fichiers


La fonction `open()` ouvre un fichier et retourne un objet fichier correspondant qui vous permet d'interagir avec le fichier (lire son contenu, y écrire, etc.). La méthode `read()` lit les données d'un fichier ouvert. La méthode `write()` écrit des données dans un fichier ouvert.

In [82]:
# écrire dans un fichier
message = "Bonjour le monde"
with open("bonjour.txt", "w") as file:
    file.write(message)
# Note: Avec 'with', le fichier est automatiquement fermé à la fin du bloc
# Pas besoin d'appeler file.close() explicitement

In [83]:
# lire un fichier
with open("bonjour.txt", "r") as file:
    text = file.read()
    print(text)
# Le fichier est automatiquement fermé ici

Bonjour le monde


In [84]:
# écrire dans un fichier
message1 = "Bonjour le monde"
message2 = "Programmation en Python"
with open("bonjour.txt", "w") as file:
    file.write(message1)
    file.write(message2)

In [85]:
# lire un fichier
with open("bonjour.txt", "r") as file:
    text = file.read()
    print(text)

Bonjour le mondeProgrammation en Python


In [86]:
# Rédaction dans un fichier en utilisant le caractère de nouvelle ligne
message1 = "Bonjour le monde\n"
message2 = "Programmation en Python"
with open("bonjour.txt", "w") as file:
    file.write(message1)
    file.write(message2)

with open("bonjour.txt", "r") as file:
    text = file.read()
    print(text)

Bonjour le monde
Programmation en Python


Dans Jupyter Notebook, le symbole `?` est utilisé pour accéder à la documentation et à l'aide des fonctions et objets. C'est un raccourci pour accéder au système d'aide intégré dans Python et les environnements Jupyter.

In [87]:
?open

Signature:
open(
    file,
    mode='r',
    buffering=-1,
    encoding=None,
    errors=None,
    newline=None,
    closefd=True,
    opener=None,
)
Docstring:
Open file and return a stream.  Raise OSError upon failure.

file is either a text or byte string giving the name (and the path
if the file isn't in the current working directory) of the file to
be opened or an integer file descriptor of the file to be
wrapped. (If a file descriptor is given, it is closed when the
returned I/O object is closed, unless closefd is set to False.)

mode is an optional string that specifies the mode in which the file
is opened. It defaults to 'r' which means open for reading in text
mode.  Other common values are 'w' for writing (truncating the file if
it already exists), 'x' for creating and writing to a new file, and
'a' for appending (which on some Unix systems, means that all writes
append to the end of the file regardless of the current seek position).
In text mode, if encoding is not specified

In [88]:
?message1

Type:        str
String form: Bonjour le monde
Length:      17
Docstring:  
str(object='') -> str
str(bytes_or_buffer[, encoding[, errors]]) -> str

Create a new string object from the given object. If encoding or
errors is specified, then the object must expose a data buffer
that will be decoded using the given encoding and error handler.
Otherwise, returns the result of object.__str__() (if defined)
or repr(object).
encoding defaults to 'utf-8'.
errors defaults to 'strict'.

In [89]:
?message2

Type:        str
String form: Programmation en Python
Length:      23
Docstring:  
str(object='') -> str
str(bytes_or_buffer[, encoding[, errors]]) -> str

Create a new string object from the given object. If encoding or
errors is specified, then the object must expose a data buffer
that will be decoded using the given encoding and error handler.
Otherwise, returns the result of object.__str__() (if defined)
or repr(object).
encoding defaults to 'utf-8'.
errors defaults to 'strict'.

Le code suivant ouvre le fichier "bonjour.txt" en mode lecture, lit son contenu, l'affiche, puis ferme le fichier.

In [90]:
with open("bonjour.txt", "r") as file:
    text = file.read()
    print(text)

Bonjour le monde
Programmation en Python


### b\. readline()

Cette fonction peut être utilisée pour lire un fichier ligne par ligne et non le contenu complet en un seul appel comme read()

In [91]:
message1 = "Bonjour le monde\n"
message2 = "Programmation en Python"
with open("bonjour.txt", "w") as file:
    file.write(message1)
    file.write(message2)

Utilisez `readline()` dans une boucle ou de manière itérative pour traiter chaque ligne d'un fichier séquentiellement. Cela est utile pour traiter des fichiers volumineux ou des fichiers où il est nécessaire de traiter chaque ligne indépendamment.

In [92]:
with open("bonjour.txt", "r") as file:
    text = file.readline()
    print(text)

Bonjour le monde



In [93]:
message1 = "Bonjour le monde\n"
message2 = "Programmation en Python\n"
with open("bonjour.txt", "w") as file:
    file.write(message1)
    file.write(message2)

In [94]:
with open("bonjour.txt", "r") as file:
    for line in file:
        print(line)

Bonjour le monde

Programmation en Python



### c. Gestion des exceptions

Lorsque vous travaillez avec des fichiers, beaucoup de choses peuvent mal tourner : le fichier pourrait ne pas exister, vous pourriez ne pas avoir la permission de le lire, ou le disque pourrait être plein. La gestion des exceptions permet à votre programme de gérer ces erreurs gracieusement.

In [95]:
# Sans gestion des exceptions - cela planterait si le fichier n'existe pas
# with open("fichier_inexistant.txt", "r") as file:
#     content = file.read()

# Avec gestion des exceptions - le programme continue même si le fichier n'existe pas
try:
    with open("fichier_inexistant.txt", "r") as file:
        content = file.read()
        print(content)
except FileNotFoundError:
    print("Erreur: Le fichier n'a pas été trouvé. Veuillez vérifier le nom du fichier.")
except PermissionError:
    print("Erreur: Vous n'avez pas la permission de lire ce fichier.")
except Exception as e:
    print(f"Une erreur inattendue s'est produite: {e}")

Erreur: Le fichier n'a pas été trouvé. Veuillez vérifier le nom du fichier.


Le bloc `try-except` vous permet de :
- **try** : Essayer d'exécuter du code qui pourrait causer une erreur
- **except** : Gérer gracieusement des types spécifiques d'erreurs
- **finally** (optionnel) : Exécuter du code indépendamment de la survenue d'une erreur

In [96]:
# Un exemple pratique : lire un fichier en toute sécurité
def lire_fichier_securise(nom_fichier):
    """Lit un fichier et retourne son contenu, ou None si une erreur survient"""
    try:
        with open(nom_fichier, "r") as file:
            return file.read()
    except FileNotFoundError:
        print(f"Le fichier '{nom_fichier}' n'a pas été trouvé.")
        return None
    except Exception as e:
        print(f"Erreur lors de la lecture du fichier: {e}")
        return None

# Test avec un fichier existant
contenu = lire_fichier_securise("bonjour.txt")
if contenu:
    print("Contenu du fichier:", contenu)

# Test avec un fichier inexistant
contenu = lire_fichier_securise("nexiste_pas.txt")

Contenu du fichier: Bonjour le monde
Programmation en Python

Le fichier 'nexiste_pas.txt' n'a pas été trouvé.


**Question 1:** Copiez un fichier HTML dans votre répertoire. Écrivez un programme
en Python pour obtenir les valeurs suivantes :

- nombre de caractères dans le fichier HTML
- nombre de lignes dans le fichier HTML
- nombre de mots dans le fichier HTML
- les vingt premiers mots du fichier HTML
- des mots distincts dans le fichier HTML

**Indices:**
- Utilisez `len()` pour compter les caractères
- Utilisez `split()` pour diviser le texte en mots
- Utilisez un `set` pour trouver les mots distincts
- Envisagez de lire ligne par ligne et d'accumuler les comptages

**Question 2:** Modifiez votre programme pour gérer les erreurs gracieusement :
- Si le fichier n'existe pas, affichez un message d'erreur convivial
- Si le fichier est vide, affichez "Le fichier est vide"
- Enveloppez vos opérations sur les fichiers dans un bloc `try-except`

**Question 3:** Copiez le fichier CSV
population.csv du dossier **data**. Le fichier contient les valeurs de population entre
1901 et 2016. Écrivez un programme en Python pour obtenir :

- la valeur maximale de la population
- la valeur minimale de la population

**Indices:**
- Vous pouvez utiliser `split(",")` pour séparer les valeurs de chaque ligne
- Utilisez `int()` pour convertir les valeurs de chaîne en entiers
- Utilisez les fonctions `max()` et `min()` sur une liste de valeurs de population
- Alternativement, vous pouvez utiliser la fonction `loadtxt()` de NumPy (voir Exercice 6)

## Exercise 6 ★★★

### NumPy

**NumPy**, une bibliothèque populaire pour les calculs numériques, offre des moyens efficaces d'effectuer des opérations mathématiques sur des tableaux, y compris des matrices. Les opérations NumPy sont optimisées pour les performances, en particulier avec de grands ensembles de données.

In [1]:
import numpy as np

### a. Les opérations sur les matrices

In [2]:
a1 = [1, 2, 3, 4]
b1 = [5, 6, 7, 8]

Addition de matrices avec `np.add()`

In [3]:
c1 = np.add(a1, b1)
print(c1)

[ 6  8 10 12]


Soustraction de matrices avec `np.subtract()`

In [4]:
c1 = np.subtract(a1, b1)
print(c1)

[-4 -4 -4 -4]


Multiplication de matrices avec `np.multiply()`

In [5]:
c1 = np.multiply(a1, b1)
print(c1)

[ 5 12 21 32]


In [6]:
c1 = np.multiply(4, b1)
print(c1)

[20 24 28 32]


L'objectif de `np.dot` est de calculer le produit scalaire (ou produit matriciel) entre deux tableaux NumPy `a1` et `b1`.

- Si `a1` et `b1` sont des **vecteurs** (tableaux 1D), alors `np.dot(a1, b1)` renvoie le **produit scalaire** des deux vecteurs, qui est un nombre unique obtenu en multipliant les éléments correspondants des vecteurs et en les additionnant.
  
- Si `a1` et `b1` sont des **matrices** (tableaux 2D), alors `np.dot(a1, b1)` calcule le **produit matriciel** entre les deux matrices.

`np.dot` est utilisé pour effectuer un produit scalaire (ou matriciel) en fonction des dimensions des entrées.

In [7]:
c1 = np.dot(a1, b1)
print(c1)

70


In [8]:
c1 = np.dot(5, b1)
print(c1)

[25 30 35 40]


In [9]:
b1 = [5, 6, 7, 8]
c1 = np.dot(a1, b1)
print(c)

NameError: name 'c' is not defined

La fonction `np.average()` de NumPy permet de calculer la **moyenne pondérée** (ou moyenne arithmétique) d'un tableau ou d'une liste de valeurs. Par défaut, elle calcule la moyenne simple, mais elle offre également la possibilité d'utiliser des **poids** pour chaque élément du tableau, si spécifié.


In [10]:
a1 = [1, 2, 3, 4, 5 ]
moyen = np.average(a1)
print(moyen)

3.0


### b. Tranposition matricielle

L'objectif de `b1.T` en NumPy est d'afficher la **transposée** du tableau `b1`, c'est-à-dire d'inverser ses dimensions. Si `b1` est un vecteur ou une matrice, la transposition échange les lignes et les colonnes.

In [11]:
b1 = [[5, 6, 7, 8, 9], [1, 2, 3, 4, 5]]
print(b1)
b1 = np.array(b1)
print(b1.T)

[[5, 6, 7, 8, 9], [1, 2, 3, 4, 5]]
[[5 1]
 [6 2]
 [7 3]
 [8 4]
 [9 5]]


### c. Séparer une matrice en deux, horizontalement et verticalement

La fonction `np.hsplit()` divise un tableau horizontalement (le long des colonnes) aux indices spécifiés.

In [12]:
a = [[0, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 1]]
a = np.array(a)

a = np.hsplit(a, [2])

a1 = a[0]
a2 = a[1]
print(a1)
print(a2)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [0]
 [0]
 [1]]


In [13]:
?np.hsplit

Signature:       np.hsplit(ary, indices_or_sections)
Call signature:  np.hsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function hsplit at 0x000002521022BA60>
File:            c:\users\charl\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays horizontally (column-wise).

Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis except for 1-D arrays, where it is split at ``axis=0``.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> import numpy as np
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.hsplit(x, 2)
[array([[  0.,  

La fonction `np.vsplit()` divise un tableau verticalement (le long des lignes) aux indices spécifiés.

In [14]:
?np.vsplit

Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x000002521022BB00>
File:            c:\users\charl\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> import numpy as np
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
   

In [15]:
a = [[0, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 1]]
a = np.array(a)

a = np.vsplit(a, [2])

a1 = a[0]
a2 = a[1]
print(a1)
print(a2)

[[0 0 0]
 [0 1 0]]
[[1 0 0]
 [1 1 1]]


### d. Les opérations sur les matrices bidimensionnelles

In [16]:
a2 = [[1, 2, 3, 4], [1, 2, 3, 4]]
b2 = [[5, 6, 7, 8], [5, 6, 7, 8]]

In [17]:
c2 = np.add(a2, b2)
print(c2)

[[ 6  8 10 12]
 [ 6  8 10 12]]


In [18]:
c2 = np.subtract(a2, b2)
print(c2)

[[-4 -4 -4 -4]
 [-4 -4 -4 -4]]


In [19]:
c2 = np.multiply(a2, b2)
print(c2)

[[ 5 12 21 32]
 [ 5 12 21 32]]


In [20]:
a2 = [[1, 2, 3, 4], [1, 2, 3, 4]]
a2 = np.array(a2)
b2 = [[5, 6, 7, 8], [5, 6, 7, 8]]
b2 = np.array(b2)
c2 = np.dot(a2, b2.T)
print(c2)

[[70 70]
 [70 70]]


### e. Redéfinir une matrice

**.reshape()** : L'objectif de `b2.reshape(m, n)` en NumPy est de **redimensionner** le tableau `b2` en une nouvelle forme avec **m lignes et n colonnes**. Cette méthode réorganise les éléments de `b2` sans en modifier les valeurs, tant que le nombre total d'éléments reste le même. 

Par exemple, si `b2` a 8 éléments au total, `b2.reshape(4, 2)` les réarrangera en un tableau 2D de 4 lignes et 2 colonnes.

In [21]:
b2.reshape(4, 2)
print(b2)

[[5 6 7 8]
 [5 6 7 8]]


### f. Créer des matrices avec des nombres aléatoires

**`np.random.rand()`** génère un tableau de nombres aléatoires uniformément distribués entre 0 et 1. **`np.zeros()`** crée un tableau rempli de zéros de la forme spécifiée.

In [22]:
a = np.random.rand()
print(a)

0.7726270505514662


In [23]:
a = np.random.rand(1)
print(a)

[0.58600751]


In [24]:
a = np.random.rand(2, 5)
print(a)

[[0.26814072 0.4767117  0.21906536 0.42758941 0.96429153]
 [0.56441504 0.83836332 0.2835308  0.62951205 0.54330171]]


In [25]:
a = np.random.rand(2, 3, 3)
print(a)

[[[0.67673199 0.46491461 0.09220615]
  [0.43206766 0.22211816 0.0166128 ]
  [0.55934537 0.97920463 0.93239596]]

 [[0.12980938 0.36521679 0.49301638]
  [0.14650535 0.75383085 0.53884071]
  [0.67321886 0.41312906 0.3621975 ]]]


In [26]:
a = np.zeros(1)
print(a)

[0.]


In [27]:
a = np.zeros(1, dtype=int)
print(a)

[0]


In [28]:
a = np.zeros((2, 5), dtype=int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]]


**Question:** Lisez les données présentes dans le fichier population.csv dans des tableaux en utilisant les fonctions numpy et calculez les valeurs suivantes:

- la valeur maximale de la population et l'année
- la valeur minimale de la population et l'année
